#!/usr/bin/ruby
require 'colorize'
load '/etc/timepatrol/config'

def now
 Time.new.strftime "%Y.%m.%d;%H:%M:%S"
end


def if_letter_then_abort(selid)
  if [*'a'..'z',*'A'..'Z'].include? selid
    puts format_message("ABORTED.",1)
    abort
  end
end


def snapid
  ids = `btrfs subvolume list / | grep #{SNAPSHOTS_VOLUME}/`
  id_list=[]
  ids.split("\n").each do |i|
    id_list<<i.split('/')[1].to_i
  end
  return id_list.sort
end


def snapshot(comm,keep,fake)
  id = snapid.last.to_i + 1
  path = SNAPSHOTS_FOLDER + '/' + id.to_s
  kernel = `uname -r`.chomp
  `mkdir #{path}`
  comm ||= ''
  unless fake 
    puts `btrfs subvolume snapshot / #{path}/data` 
    File.write('/tmp/timepatrol_last_snapshot',path,mode:'w')
  end
  comm = comm.gsub(';','')
  info = "#{now};#{comm};#{kernel};#{keep}"
  File.write("#{path}/info",info,mode:'w')
end



def splitstr(string,shift)
  max = 35
  line = ''
  total = 0
  string.gsub!('/','/ ')
  string.split(' ').each do |s|
    scut = s[0..max]
    total = total + scut.size
    if total < max
      line = line + scut + ' '
    else
      total = scut.size
      line = line + "\n" + ' '*shift + scut + ' ' 
    end
  end
  line.gsub!('/ ','/')
  return line
end



def readinfo(id)
  path = SNAPSHOTS_FOLDER + '/' + id.to_s
  unless Dir.exist? path then puts format_message("There is\
 no snapshot ID [#{id}].",1); abort end
  info = File.read(path + '/info').strip.split(';')
  date  = info[0]
  time  = info[1]
  desc  = info[2]
  kernel= info[3]
  keep  = info[4]
  comm  = splitstr(desc,45)
  return date,time,comm,kernel,keep
end



def colorline(string,index)
  if index.odd? 
    string = string.white 
  else
    string.light_white 
  end
  return string
end



def list(opt)


    nline = 84
    title = ":: TIMEPATROL SNAPSHOTS ::"
    tlhalf = title.length/2

    
    legend= ' '*3+"ID"\
      +' '*3+"DATE"\
      +' '*8+"TIME"\
      +' '*6+"KERNEL"\
      +' '*9+"COMMENT"
    
        
    puts lineline = ("=".light_white)*nline
    puts " "*(nline/2-tlhalf) + title.yellow.bold
    puts lineline
    puts legend.bold

    
    snapid.each.with_index do |id,index|
      date, time, comm, kernel, keep = readinfo(id)
      unless opt == 'list-verbose' then comm = comm[0..150].strip end
      showinfo(id,date,time,comm,kernel,keep,index)
    end


    puts line = ("-".light_white)*nline
    puts "TOTAL: #{snapid.length}".bold
    
    
    unless opt == 'list' or opt == 'list-verbose'  
      if opt == 'rollback' then opt += ' to' end
      opt = opt.magenta
      puts format_message("Select a snapshot to #{opt}\
 or type any letter to ABORT:",0)
    end

end


def rollback(array_selected)
  countdown = 10 # seconds before rebooting
  rollid = array_selected.first 
  kernel_from = `uname -r`.chomp 
  kernel_to = readinfo(rollid)[3]


  if array_selected.length != 1 then puts format_message("You\
 must choose a single ID. ABORTED.",1);abort end


  if kernel_from != kernel_to
    puts format_message("Running kernel (#{kernel_from}) is\
 different from snapshot [#{rollid}] kernel. ABORTED.",1)
    abort
  end
  

  puts format_message("Rolling back to the following snapshot:",0)
  date, time, comm, kernel, keep = readinfo(rollid)
  showinfo(rollid, date, time, comm, kernel, keep, 1)


  puts format_message("Confirm? [y/N]",2)
  
  if STDIN.gets.chomp == 'y' 
    `mkdir #{MOUNT_POINT} && mount -o subvolid=5 #{DEVICE} #{MOUNT_POINT}`
    
    check_root = Dir.exists? MOUNT_POINT+'/'+ROOT_VOLUME
    check_snap = Dir.exists? MOUNT_POINT+'/'+SNAPSHOTS_VOLUME
    unless check_root and check_snap
      puts format_message("Mounting stage went wrong. ABORTED.",1)
      abort
    end
   

    id = snapid.last + 1
    date, time = readinfo(rollid)

    snapshot("PRE: rollback to [#{date} #{time}]",0,true) 
    
    `mv #{MOUNT_POINT}/#{ROOT_VOLUME} #{MOUNT_POINT}/#{SNAPSHOTS_VOLUME}/#{id}/data`
    `btrfs subvolume snapshot #{MOUNT_POINT}/#{SNAPSHOTS_VOLUME}/#{rollid}/data #{MOUNT_POINT}/#{ROOT_VOLUME}`
    list_subvol = `btrfs subvolume list /`.split("\n")
    list_subvol.each do |subvol|
      data = subvol.split(' ')
      if data[8] == ROOT_VOLUME 
        `btrfs subvolume set-default #{data[1]} /`
        break
      end
    end

   
    `umount #{MOUNT_POINT} && rm -r #{MOUNT_POINT}`

    puts format_message("Confirmed. Rebooting in...",0)
      (countdown-1).times do |i| 
        puts countdown-=1
        sleep 1
      end
      puts 'BUCKLE UP!'
      sleep 1
    `reboot`
  
  else
    puts format_message('ABORTED.',1)
  end
end



def showinfo(id,date,time,comm,kernel,keep,index)
  space = 4 - id.to_s.size
  kspace = 15 - kernel.size
  
  id_string = colorline("[#{id}]",index)
  date = colorline(date,index)
  time = colorline(time,index)
  comm = colorline(comm,index)
  kernel = colorline(kernel,index)
  
  if keep == '1' then id_string = id_string.green.bold   end
  
  puts ' '*space\
    +id_string+\
    +' '*2+date\
    +' '*2+time\
    +' '*2+kernel\
    +' '*kspace+comm
end



def select(selid)
  special = false
  array_selected = []
  keyword = ['date=','time=','comment=','kernel=','keep=']
  
  keyword.map {|k| if selid.include? k then special=true; break end}
  if special
    5.times do |j|
      snapid.each do |id|
        string = readinfo(id)[j]
        if string.include? selid.sub(keyword[j],'')
          array_selected<<id
        end
      end
    end
  else
    selid.split(',').each do |item|
      if item.include? '-' 
        selid_i = item.split('-').first.to_i
        selid_f = item.split('-').last.to_i
        if selid_i >= selid_f 
          puts format_message("Bad range. ABORTED.",1)
          abort 
        end
        snapid.each do |id|
          if id >= selid_i and id <= selid_f
            array_selected<<id
          end
        end
      else
        snapid.include? item
        array_selected<<item
      end
    end 
  end
  
  if array_selected.empty?
    puts format_message("No snapshot meets the given criteria.",1)
    abort
  end

  return array_selected
end



def grep_string(array_selected,substring)
  array_selected.each do |id|
     date, time, comm, kernel, keep = readinfo(id)
     comm.gsub!(substring,substring.bold)
     showinfo(id,date,time,comm,kernel,keep,1)
  end
end



def delete(array_selected)

  array_selected.each.with_index do |id,index|
    date,time,comm,kernel,keep = readinfo(id)
    showinfo(id,date,time,comm,kernel,keep,index)
  end


  puts format_message("Confirm deletion of the selected snapshot(s) above? [y/N]",2)
  ans = STDIN.gets.chomp


  if ans == 'y' 
    puts format_message("Confirmed.",0)
    array_selected.each do |id|
      code1 = `btrfs subvolume delete #{SNAPSHOTS_FOLDER}/#{id}/data; echo $?`.to_i
      code2 = `rm -r #{SNAPSHOTS_FOLDER}/#{id}; echo $?`.to_i 
      if code1.abs+code2.abs > 0 then puts "FAILED deleting snapshot [#{id}]." end
    end
  else 
    puts format_message('ABORTED.',1)
  end

end




def repack
  puts "Repacking snapshots..."
  path = SNAPSHOTS_FOLDER+'/'
  snapid.each.with_index do |v,j|
    from = path+v.to_s
    to = path+(j+1).to_s
    if from != to
      `mv #{from} #{to}`
      puts "#{v} --> #{j+1}"
    end
  end
end


def prune
  count = 0
  keep_count = 0
  snapid.map{ |id| if readinfo(id)[4]=='1' then keep_count+=1 end }
  maxdel = snapid.length - (MAXIMUM_SNAPSHOTS + keep_count)
  
  snapid.each do |id|
    if count >= maxdel then break end
    unless readinfo(id)[4]=='1'
      code1 = `btrfs subvolume delete #{SNAPSHOTS_FOLDER}/#{id}/data; echo $?`.to_i
      code2 = `rm -r #{SNAPSHOTS_FOLDER}/#{id}; echo $?`.to_i 
      if code1.abs + code2.abs > 0 
        puts "FAILED pruning snapshot [#{id}]. ABORTED."
      else
        puts "pruning snapshot [#{id}]."
        count += 1
      end
    end
  end
end


def mark(array_selected)
  array_selected.each do |id|
    file = SNAPSHOTS_FOLDER+'/'+id.to_s+'/info' 
    date, time, comm, kernel = readinfo(id)
    keep = (-readinfo(id)[4].to_i+2)/2
    info = date+';'+time+';'+comm+';'+kernel+';'+keep.to_s
    File.write(file,info,mode:'w')
  end
end


def format_message(message,mode)
  if mode == 0 then sign = ":: ".blue.bold end #Informative
  if mode == 1 then sign = ":: ".red.bold end #Aborted
  if mode == 2 then sign = ":: ".yellow.bold end #User decision
  return sign+message.bold
end


def help
  puts '------------------------------'.bold
  puts 'USAGE:    timepatrol [COMMAND]'.bold
  puts '------------------------------'.bold
  puts 'COMMANDS:'.yellow.bold
  puts "          snapshot 'COMMENT'"
  puts "          snapshot-keep 'COMMENT'"
  puts "          toggle-keep"
  puts '          delete'
  puts '          rollback'
  puts '          list'
  puts '          list-verbose'
  puts '          list-grep'
end



#=======================================

unless ENV['USER'] == 'root'
  puts format_message("You must run as root. ABORTED.",1)
  abort
end




option = ARGV[0]
selid = ARGV[1]
option ||= 'help' 




special_options = ['delete','rollback','toggle-keep']
if selid.nil? and special_options.include? option
  list(option)
  selid = STDIN.gets.chomp
  if_letter_then_abort(selid)
end





if option == 'snapshot' or option == 'snapshot-keep'
  keep = 0
  if option == 'snapshot-keep' then keep = 1 end 
  snapshot(selid,keep,false)
  if snapid.length >= MAXIMUM_SNAPSHOTS then prune end
  if snapid.last > 9990 then repack end

elsif   option == 'list' or option == 'list-verbose'
  list(option)

elsif  option == 'list-grep'
  selid ||= abort
  grep_string(select("comment="+selid),selid)

elsif option == 'rollback'
  if Dir.exists? MOUNT_POINT 
    puts format_message("The '#{MOUNT_POINT}' folder shouldn't exist. ABORTED.",1)
    abort 
  end
  rollback(select(selid))

elsif option == 'delete'
  delete(select(selid))

elsif option == 'toggle-keep'
  mark(select(selid))

elsif option == 'help' 
  help

else
  help
  puts format_message("There is no '#{option}' option. ABORTED",1)

end

