#!/usr/bin/ruby
first_stage = []
second_stage = []
actions = ''

pacman_log = (File.readlines '/var/log/pacman.log').reverse

pacman_log.each do |line|
  if line.include? '05-timepatrol-pre.hook' then break end
  first_stage<<line
end

first_stage.reverse.each do |line|
  if line.include? 'transaction completed' then break end
  unless line.include? 'transaction started' then second_stage<<line end
end

second_stage.each.with_index do |line,index|
  actions += line.split('[ALPM]').last.strip
end

`/usr/local/bin/timepatrol snapshot "POST: #{actions}"`
