#!/usr/bin/ruby
# frozen_string_literal: true

@magic_string = '@PACMAN-PRE-HOOK'

def change_string(actions, path)
  info = File.read("#{path}/info")
  info.sub!(@magic_string, "PRE: #{actions}")
  File.write("#{path}/info", info, mode: 'w')
end

`/usr/bin/timepatrol snapshot #{@magic_string}` if ARGV[0] == 'pre'

if ARGV[0] == 'post'

  path = File.read('/tmp/timepatrol_last_snapshot').strip
  pacman_lock_file = "#{path}/data/var/lib/pacman/db.lck"
  `rm #{pacman_lock_file}` if File.exist? "#{path}/data/var/lib/pacman/db.lck"

  first_stage = []
  second_stage = []
  actions = ''

  (File.readlines '/var/log/pacman.log').reverse.each do |line|
    break if line.include? 'timepatrol-pre.hook'

    first_stage << line
  end

  first_stage.reverse.each do |line|
    break if line.include? 'transaction completed'

    second_stage << line unless line.include? 'transaction started'
  end

  second_stage.each.with_index do |line, index|
    unless line.include?('[ALPM-SCRIPTLET]')
      actions += line.split('[ALPM]').last.strip
      actions += ', ' if index + 1 < second_stage.length
    end
  end

  actions.gsub!('upgraded', 'upgrade')
  actions.gsub!('installed', 'install')
  actions.gsub!('removed', 'remove')
  actions.gsub!('downgraded', 'downgrade')

  change_string(actions, path)
end
